<a href="http://www.tolidat.ir/company/type/تولیدی/category/100">فلزات غیر آهنی (آلومینیوم،مس و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/101">آلومینیوم و فرآورده های آلومینیومی و پروفیل آلومینیوم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/102">ورقهای آلومینیوم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/103">درب و پنجره آلومینیومی، متعلقات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/104">انواع نمای ساختمان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/105">شمشهای آلومینیوم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/106">ظروف و قطعات آلومینیوم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/107">نرده و حفاظ های آلومینیوم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/108">انواع آلیاژ ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/109">فرآورده های مسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/110">فرآورده های سرب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/111">فرآورده های روی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/112">فرآورده های برنجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/113">سایر فلزات غیر آهنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/201">تبلیغات الکترونیکی و غیر الکترونیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/202">بازاریابی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/203">موسسات کاریابی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/204">پرچمهای تبلیغاتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/205">بانکهای اطلاعاتی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/206">خبرگزاری و اطلاع رسانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/207">طراحی صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/208">صنعت فیلم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/209">سامانه های پیام کوتاه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/301">تجهیزات و لوازم کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/302">ماشین آلات کشاورزی و جنگلداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/303">خدمات کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/304">تجهیزات آبیاری - سیستمهای آبیاری - استخرهای کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/305">مواد محافظتی گیاهان و آفت کشها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/306">مواد تقویت کننده کشاورزی (آلی، بیولوژیک، شیمیایی)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/307">گلخانه و تجهیزات گلخانه ای</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/308">خشکبار (کشمش، پسته، آجیل و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/309">گلها، درختان، گیاهان تزئینی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/310">میوه جات و سبزیجات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/311">فرآورده های کشاورزی (بذرها، حبوبات، برنج و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/312">خرما</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/313">زعفران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/314">چای، قهوه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/315">قارچ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/316">مجتمع های کشت و صنعت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/317">خوراک دام و طیور </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/318">تجهیزات و تأسیسات دامداری و مرغداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/319">دامداری و مرغداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/320">تولید ماهیان دریایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/321">داروهای دامی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/322">تولید تخم مرغ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/400">باربری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/401">شرکتهای تاکسیرانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/402">شرکت های پستی داخلی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/403">کشتیرانی و حمل و نقل بین المللی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/501">سیستم تهویه مطبوع - چیلر - فن کوئل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/502">خشک کننده هوا - تمیز کننده هوا (ایر کلینر) - ایر واشر - فیلتر هوا - دستگاههای رطوبت ساز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/503">فن ها - دستگاههای تهویه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/504">قطعات یدکی برای سیستمهای تهویه مطبوع و...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/505">کولرهای صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/506">سردخانه - یخچالهای صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/507">برجهای خنک کننده - کندانسورهای هوای سرد</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/508">قطعات یدکی برای سیستمهای برودتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/509">دستگاههای بستنی ساز - دستگاههای یخ ساز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/510">یخچالهای ویترینی - یخچالهای مخصوص</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/511">بویلرها و مخازن، دیگ ها و منبع ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/512">مشعل ها و کوره ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/513">رادیاتورهای گرمایشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/514">سیستم های سرمایش - انواع کولر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/515">قطعات یدکی،اندازه گیری های فشار و حرارت، ترموکوبل ها و مبدل های حرارتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/600">ابزار آلات صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/601">ابزار آلات کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/602">انواع برس، قلم موهای نقاشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/603">تجهیزات جوشکاری، الکترود، ترانس های جوشکاری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/604">ابزار هیدرولیک، ابزار بادی، ابزار دقیق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/605">ابزار کار روی فلز، ابزار الماسه، ابزار برشی، لیزر، خدمات لیزر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/606">ابزار کار روی چوب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/607">ابزار آلات برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/701">ملحفه، حوله ها، انواع تشک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/702">پتو، پرده، انواع پوشش ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/703">انواع پارچه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/704">گونی، برزنت، کیسه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/705">نخ، الیاف، انواع تور، کش، نخ پنبه ای</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/706">خدمات، مواد اولیه برای نساجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/707">قطعات یدکی ماشین های نساجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/801">اتوماسیون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/802">ابزار دقیق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/900">خودرو و وسایل نقلیه دو چرخ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/901">قطعات خودرو - بدنه - موتور خودرو - شاسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/902">دوچرخه و قطعات دوچرخه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/903">اتوبوسها - سواریها - کامیون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/904">موتور سیکلتها و قطعات موتور سیکلتها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/905">طراحی مهندسی خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/906">وسایط  نقلیه چند منظوره ، انواع تریلر، خودروهای خاص</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/907">آئینه و شیشه های خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/908">خدمات پس از فروش لوازم خانگی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1001">خدمات حسابداری </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1002">خدمات اعزام دانشجو و نیروی کار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1003">خدمات تهیه غذا (کترینگ)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1004">مشاوره مهاجرت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1005">خدمات مسکن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1006">خدمات نظافتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1007">خدمات انبار و سردخانه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1008">خدمات موسیقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1009">خدمات طلا و جواهر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1010">خدمات فروشگاه های زنجیره ای</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1011">تأمین نیروی انسانی ( تخصصی و غیر تخصصی )</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1012">خدمات مشاوره حقوقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1013">ثبت شرکت ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1014">دارالترجمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1015">موسسات حفاظتی و مراقبتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1016">دفاتر پیشخوان دولت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1101">آجر - سفال</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1102">سیمان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1103">کاشی - موزائیک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1104"> لوله ها و صفحات آزبستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1105">گچ - پودر گچ - آهک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1106">قطعات پیش ساخته - سقف کاذب - بلوک </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1107">فرآورده های نسوز دیر گداز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1108">آسفالت - پوششهای سقف - دیوار </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1109">شن - ماسه - خاک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1110">سنگها - سنگهای ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1111">لوازم بهداشتی ساختمان (وان - جکوزی -سونا - استخر)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1113">کف کاذب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1114">خانه های پیش ساخته (کاروان - کانکس و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1115">انواع چینی و سرامیک های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1116">مواد خام برای صنعت چینی و سرامیک، لعاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1117">درب و پنجره های UPVC</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1118">شیشه های ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1119">آئینه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1120">درب های  ضد سرقت ساختمان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1200">فرش دستباف</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1201">فرش و موکت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1204">صنایع دستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1300">سندیکاها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1400">سایر مواد شیمیایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1401">چسب ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1402">مرکب چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1403">رنگها - رزینها - رنگهای نساجی - رنگ برای چرم - مواد اولیه صنایع رنگسازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1404">پاک کننده های صنعتی - الکل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1405">مواد شیمیائی عکاسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1406">مواد شیمیائی خام - نگهدارنده ها - پوششهای ضد سایش و خوردگی - شوینده های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1407">مواد شیمیائی خاص - مواد  اولیه شیمیائی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1408">واکس ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1409">آبکاری - گالوانیزاسیون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1411">انواع اسید</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1412">بتن و فرآورده های بتنی - افزودنی های بتن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1500">صنعت ورزش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1501">تجهیزات پیک نیک (کمپینگ) - چادرهای امدادی و مسافرتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1502">مراکز ورزشی (مبلمان، طراحی، ساخت و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1503">کالاهای ورزشی، تجهیزات بدنسازی، کلاه ایمنی، تابلوهای ورزشی، کفپوش های ورزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1504">باشگاه های ورزشی و مراکز تفریحی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1505">فدراسیون های ورزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1600">لوازم التحریر و طراحی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1601">لوازم التحریر و طراحی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1701">پوشاک چرمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1702">پوشاک رو (کت - شلوار - مانتو و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1703">پوشاک ورزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1704">لباس زیر - جوراب ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1705">لباس کار - لباس پرسنلی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1706">ملزومات لباس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1707">کفش، زیره کفش، صندل و دمپایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1708">چرم مصنوعی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1709">چرم طبیعی، فرآورده های چرمی و پوست</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1710">کیف، ساک ، چمدان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1801">راه حل های جامع در زمینه IT,ICT اطلاعات و ارتباطات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1802">سخت افزار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1803">نرم افزار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1804">ارائه خدمات اینترنت و سرویس های تلفن بین الملل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1805">سیستم های مبتنی بر بارکد</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1901">مهندسین مشاور در زمینه کشاورزی و جنگلداری - منابع طبیعی - محیط زیست - فضای سبز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1902">مهندسین مشاور در زمینه پروژه های معماری و شهرسازی - ساختمان سازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1903">مهندسین مشاور در زمینه صنایع مختلف </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1904">مهندسین مشاور در زمینه طرح های صنعت برق - انرژی - نیروگاه های برق - خطوط انتقال انرژی - پستهای برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1905">مهندسین مشاور در زمینه طرح های صنعتی - ساخت کارخانجات - قطعات صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1906">مهندسین مشاور در زمینه معدن - زمین شناسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1907">مهندسین مشاور در زمینه نفت، گاز، پتروشیمی - خطوط لوله و پالایشگاهها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1908">مهندسین مشاور در زمینه تصویر برداری هوایی - نقشه برداری - طراحی و نقشه کشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1909">مهندسین مشاور در زمینه جاده سازی - پل سازی - سدسازی - تونل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1910">مهندسین مشاور در زمینه مخابرات - اتوماسیون - کامپیوتر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1911">مهندسین مشاور در زمینه آب و فاضلاب - سیستمهای آبیاری - صنایع آب - زهکشی - منابع آبی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1912">مهندسین مشاور در زمینه راه آهن - فرودگاهها - حمل و نقل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1913">مهندسین مشاور در زمینه سازه های دریایی - پروژه های دریایی - صنایع دریایی - سازه های زیر دریایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1914">مهندسین مشاور در زمینه خدمات مدیریت - خدمات فنی و مهندسی - تأسیسات شهری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1915">سایر مهندسین مشاور</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2001">پیمانکاران در زمینه ساختمانی - فوندانسیون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2002">پیمانکاران در زمینه نصب و راه اندازی کارخانجات - صنایع - سازه های فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2003">پیمانکاران در زمینه سدسازی - راه سازی - پل سازی - تونل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2004">پیمانکاران در زمینه تأسیسات - ماشین آلات - خدمات فنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2005">پیمانکاران عمومی و پروژه های عمرانی - شهرکهای صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2006">پیمانکاران در زمینه نفت، گاز، پتروشیمی، پالایشگاههای نفت و گاز - حفاری چاه های نفت - خطوط لوله</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2007">پیمانکاران در زمینه آبیاری - زهکشی - آب و فاضلاب - صنایع آب و فاضلاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2008">پیمانکاران در زمینه صنایع اتوماسیون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2009">پیمانکاران در زمینه ژئوتکنیک - معادن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2010">پیمانکاران در زمینه شیلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2011">پیمانکاران در زمینه فرودگاه -راه آهن- ترمینال</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2012">پیمانکاران در زمینه بنادر - پروژه های دریایی - صنایع دریایی - ساخت کشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2013">سایر پیمانکاران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2100">عایق ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2101">عایق های نسوز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2102">عایق های رطوبتی - ایزوگام</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2103">عایق های حرارتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2104">عایق های برق و الکتریک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2105">آجرهای عایق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2106">عایق های ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2107">عایق های صوتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2108">عایق های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2201">لوازم خانگی برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2202">لوازم خانگی غیر برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2301">پخش مواد غذایی و نوشیدنیها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2302">تجهیزات پزشکی - دارو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2400">مراکز آموزشی و کمک آموزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2401">کالج ها و دانشگاه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2402">کتابخانه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2403">مراکز آموزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2404">تجهیزات کمک آموزشی و بازی های فکری ، اسباب بازیها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2501">آنتها (گیرنده های  هوایی) - گیرنده و فرستنده های  رادیویی و تلویزونی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2502">لوازم صوتی و تصویری - رادیو و تلویزیون - نوارهای کاست - فیلم - بلندگو - سی دی - تابلوهای نمایشگر تبلیغاتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2503">باتری ها - خازن ها - آکومولاتورها - دستگاه های شارژ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2504">سیم و کابل - کابلهای مخابراتی - متعلقات - هادیات - المنت های حرارتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2505">تابلوهای برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2506">یو .پی . اس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2507">وسایل برقی صنعتی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2508">کربن و فرآورده های گرافیتی - عایقها - زغالهای صنعتی - - مقره ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2509">تجهیزات و دستگاه های مخابراتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2511">ژنراتورها، توربین ها، مبدلها، موتورهای الکتریکی و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2512">سخت افزار ها (تجهیزات و لوازم پردازش الکترونیکی)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2513">لامپ ها - وسائل و تجهیزات روشنایی و لوستر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2514">ابزارهای اندازه گیری برقی - دستگاه های اندازه گیری برقی و مهندسی - نمایشگرهای الکترونیکی و صنعتی - ابزار دقیق برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2515">نیروگاههای تولید برق - ایستگاهای  توزیع نیرو - قطعات و تجهیزات نیروگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2516">سیستم های ارتینگ - برق گیر(صاعقه گیر)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2517"> خدمات نصب در صنعت برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2518">سیستم های مدیریت هوشمند</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2519">استارتر - کنترل کننده موتور</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2520">کلیدهای اتوماتیک (قطع و وصل)، سیستم های کنترل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2521">کلید ها - پریزها - دوشاخه ها - فیوزها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2522">سیستم ها و دستگاه های زمان سنج الکتریکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2523">ترانسفورمر ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2524">برجهای انتقال نیرو - شبکه های توزیع</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2525">انرژیهای نو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2526">مشاوره - طراحی و خدمات مخابراتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2527">محصولات برقی ضد انفجار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2601">لوله و اتصالات پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2602">لوله و اتصالات فولادی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2603">لوله و اتصالات چدنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2604">لوله و اتصالات آلومینیومی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2605">لوله و اتصالات استیل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2606">لوله و اتصالات فایبرگلاس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2607">لوله و اتصالات متفرقه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2608">شیرآلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2700">محصولات و فرآورده های چوبی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2701">فرآورده های چوبی - مصنوعات چوبی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2702">نئوپان- انواع فیبر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2703">کبریت - ذغال</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2704">محصولات چوبی روکشدار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2705">سازه های چوبی ساختمان (دربها و پنجره ها)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2706">تخته های چند لایه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2800">تکنولوژی زیست محیطی و بازیافت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2801">بازیافت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2803">سازمان های حفاظت محیط زیست</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2901">مراکز تحقیقاتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2902">محصولات نانو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3000">موسسات مالی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3001">بانک ها - شرکت های اعتباری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3002">شرکت های بیمه خارجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3003">کارگزاری های بورس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3004">شرکت های سرمایه گذاری و شرکت های مادر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3005">صرافی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3006">خدمات امور بانکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3101">دوربینهای امنیتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3102">آتش خاموش کن ها - تجهیزات آتش نشان ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3103">تجهیزات ترافیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3104">کرکره های برقی و درب های شیشه ای اتوماتیک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3105">صندوق های ایمنی و غیر قابل نفوذ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3106">سیستم های ثبت تخلفات سرعت و GPS ، ردیاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3107">درب باز کن ها و آیفون های تصویری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3108">سیستم های هشدار دهنده و ایمنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3200">مواد غذایی و آشامیدنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3201">غذاهای کودک - غذاهای رژیمی - غذاهای دیابتی (قندی)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3202">نوشابه ها - آبمیوه ها - شربت - آب معدنی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3203">نان - محصولات نانی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3204">اسانس ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3205">عسل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3206">ماکارونی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3207">مارگارین و روغن نباتی - کره - روغنهای خوراکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3208">فرآورده های گوشتی، مرغ ، غذاهای دریایی، سویا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3209">فرآورده های لبنی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3210">فرآورده های آسیابی (آدر و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3211">میوه و سبزیجات کنسرو شده - سوپ - کنسروجات - ترشیجات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3212">ادویه جات - نمک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3213">قند - فرآورده های نشاسته ای - شکر - حلوا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3214">انواع سس - چاشنیها - رب گوجه فرنگی - افزودنی های نانی - افزودنی های خوراکی خمیر مایه - لواشک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3215">مواد اولیه برای صنایع غذایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3216">غذای آماده</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3300">فولاد و آهن - فرآورده های فولادی و آهنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3301">فولاد و آهن - شمش فولاد- تسمه های فولادی - ورقهای فولادی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3302">  گالوانیزه و استیل - صفحات فلزی _ ورق حلب - ورق آهن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3303">مفتولهای فلزی(آرماتور - کلاف - شاخه و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3305">مخازن فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3306">پروفیل ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3307">فولاد های آلیاژی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3308">سنگ آهن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3309">سیلوهای فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3311">سازه های فلزی - اسکلت های فلزی - سوله های فلزی - پلهای فلزی - داربستهای فلزی - قطعات فلزی پیشساخته </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3312">قوطی های فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3313">مصنوعات فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3401">نمایندگی های خارجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3402">سفارت خانه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3403">دفاتر سازمان ملل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3404">بخش ها و اتاقهای بازرگانی خارجی در ایران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3500">ریخته گری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3501">ریخته گری فولاد - ریخته گری آهن - محصولات ریخته گری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3502">ماسه های ریخته گری مورد استفاده در صنعت - مواد افزودنی ریخته گری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3600">شرکت های  بیمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3601">بیمه های مادر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3701">ساعت های حضور و غیاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3702">انواع چاپگر - چاپگرهای صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3703">کارتریج و مواد مصرفی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3704">ماشینهای اداری (فتوکپی - فاکس - ماشین حساب - بارکد خوان و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3801">وزارتخانه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3802">سازمانها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3900">شرکت های بازرگانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3901">صادر کننده ها </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3903">سازمان مناطق آزاد</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3904">وارد کننده ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3905">خدمات گمرکی و ترخیص کالا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4001">بطری های پلاستیکی و متعلقات، قطعات پلاستیکی خانگی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4002">قطعات پلاستیکی بسته بندی، پالت، کیسه های پلیمری و پلاستیکی ، انواع نخ و طناب، نایلون های ضربه گیر قوطی های پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4003">اسباب بازیهای پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4004">محصولات و قطعات لاستیکی و پلاستیکی، با کاربردهای صنعتی و اداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4005">سازه های پلاستیکی، ورق های پلاستیکی، مغازه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4006">مواد اولیه لاستیک و پلاستیک ، گرانول ، مستریچ و ... </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4007">محصولات پلاستیکی آرایشی، بهداشتی و پزشکی، دستکش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4008">فیلم های پلاستیکی و پلی اتیلنی، فیلم های استرچ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4009">استابلایزرها در صنعت پلاستیک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4010">لوازم بهداشتی پلاستیکی ساختمان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4011">قطعات و محصولا ت پلاستیکی متفرقه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4012">فایبر گلاس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4013">انواع تسمه ها، تسمه های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4014">انواع شیلنگ های صنعتی و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4015">روکش های لاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4016">تایر و تیوپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4017">اقلام  فوم، اسفنج، اسکاج، تشک، چوب پنبه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4018">یونولیت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4019">نوار تفلون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4020">انواع نایلون</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4021">پروفیل های UPVC</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4100">صدور گواهینامه های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4101">صدور گواهی نامه های بین المللی  آزمایش های فنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4102">مشاوره های فنی و مهندسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4103">برگزار کننده های نمایشگاه های بین المللی و داخلی، نمایندگی های نمایشگاه های خارجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4104">موسسات فرهنگی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4105">برگزار کننده همایش و سمینار و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4106">سایر خدمات مشاوره ای</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4107">مشاوره و خدمات مدیریت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4108">خدمات کنترل کیفیت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4201">دستگاه ها و تجهیزات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4202">مشاوره صنعتی و فنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4203">تصفیه آب و فاضلاب - پروژه های آب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4301">کابینت های آشپزخانه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4302">تجهیزات آشپزخانه صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4303">لوازم و وسایل آشپزخانه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4304">ظروف پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4400">تجهیزات آزمایشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4401">مواد شیمیایی آزمایشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4403">کابینت، مبلمان، و... برای آزمایشگاها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4404">شیشه های آزمایشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4405">خدمات آزمایشگاهی - آزمایگاههای صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4500">آژانس های مسافرتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4501">خطوط هواپیمائی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4502">هتلها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4503">آژانس های مسافرتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4601">انواع نوار چسب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4602">مواد بسته بندی (کارتن ها - جعبه و ساک مقوایی ، پاکت نامه، پاکت های صنعتی)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4603">سایر مواد بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4604">صنایع بسته بندی - بسته بندی مواد غذایی - شیشه ها و ظروف بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4605">کاغذ های حساس - کاغذ های مخصوص - فرم های تجاری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4606">برچسب ها - فویل های چسبدار</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4607">کاغذ های چاپ و تحریر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4608">لفافه های بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4609">ملزومات چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4610">مواد اولیه برای صنایع کاغذ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4611">صحافی ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4612">لیتوگرافی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4613">انواع چاپ - چاپخانه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4614">ناشرین - چاپ کتاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4615">روزنامه - مجله - ژورنال</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4616">چاپ امنیتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4701">تکنولوژی های جابجایی (نقاله ها - بالابرها و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4702">جرثقیل - بالابرهای زنجیری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4703">آسانسور و پله برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4704">جک ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4705">لیفت تراکها و سایر لیفت ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4707">پارکینگ طبقاتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4708">انواع نردبان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4800">طراحی و ساخت ماشین آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4801">ماشین آلات صنایع شیمیایی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4802">دستگاهها و ماشین های نظافتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4803">ماشین آلات صنعت پوشاک - ماشین آلات نساجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4804">ماشین آلات ساخت وساز - ماشین آلات مصالح ساختمانی و ماشین آلات راه سازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4805">ماشین آلات صنایع غذایی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4806">ماشین آلات ریخته گری - ماشین آلات متالورژی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4807">ماشین آلات لباسشویی و خوشکشویی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4808">ماشین آلات  صنایع چرم و کفش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4809">ماشین ابزار ها - ماشین ابزار های غیر برشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4810">ماشین آلات صنعت کاشی و سرامیک - ماشین آلات صنعت شیشه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4811">ماشین آلات معدن - ماشین آلات حفاری چاه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4812">ماشین آلات بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4813">ماشین آلات صنعت کاغذ - ماشین آلات چاپ - چاپ اسکرین - ماشین آلات حکاکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4814">کمپروسورها - قطعات بادی - موتورها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4815">ماشین آلات لاستیک سازی و پلاستیک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4816">ماشین آلات صنعت چوب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4817">ماشین آلات تعمیرگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4818">پمپ های هیدرولیک - پمپ ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4819">سایر ماشین آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4901">دستگاه ها و لوازم دندانپزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4902">وسایل بیمارستانی ، پنبه های بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4904">تجهیزات توانبخشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4905">مهندسی تجهیزات پزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4906">آمبولانس نجات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4907">گازهای طبی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4908">خدمات پزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4909">بیمارستان ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5000">محصولات آرایشی و بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5001">عطر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5002">محصولات بهداشتی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5003">مواد اولیه برای صنایع آرایشی و بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5004">کاغذ های بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5100">کالاها و قطعات صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5101">پیچ - مهره - پرچ - میخ - رول پلاک - واشر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5102"> چرخ دنده - زنجیر ها و متعلقات - گیربکسهای صنعتی - یاتاقان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5103">انواع قفل و یراق آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5104">انواع فنر - بست - ساچمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5105">کالاهای سیمی (توری - سیم خاردار - سیم بکسل و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5106">قطعات صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5107">تشتک ها و درب های فلزی بطری و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5108">تجهیزات مغناطیسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5109">انواع سوزن ، لوازم خیاطی فلزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5110">انواع تیغ ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5111">بلبرینگ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5112">قطعات پنوماتیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5113">چرخ های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5114">مارک های فلزی، مدال ها، کالاهای فلزی تزئینی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5115">قطعات تراشکاری شده</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5116">قالب های صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5200">صنایع دارویی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5201">توزیع کنندگان دارو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5202">انواع دارو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5203">مواد اولیه صنعت داروسازی، بسته بندی دارو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5301">فرآورده های معدنی و صنعت معدن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5401">پالایشگاه های نفت ، سوخت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5402">روغن موتور، روغن های مخصوص</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5403">گریس ها، روان کننده ها، روغن های مخصوص معدنی، فرآورده های نفتی، قیر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5404">تجهیزات نفت، گاز و پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5406">کارخانجات صنایع پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5407">پالایشگاه های گازهای صنعتی، گازهای مایع و طبیعی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5408">ساخت و نصب جایگاه های سوخت و گاز، کپسول های گاز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5500">عدسی ها - مکانیسم های دقیق - ترازوهای دقیق و باسکول ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5501">محصولات دقیق مکانیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5502">محصولات اپتیکی - عینک و متعلقات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5503">دستگاه های عکاسی و پروژکتورها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5504">ساعت های مچی و سایر ساعت ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5505">تجهیزات نقشه برداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5506">ترازوهای فروشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5507">ترازوهای آزمایشگاهی و ترازوهای دقیق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5508">ترازوهای بزرگ (باسکولها) - ترازوهای طراحی شده خاص</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5601">دکوراسیون داخلی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5602">تجهیزات و لوازم اداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5603">مبلمان خانگی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5604">پارکت ها - کفپوش ها - دیوار پوشها </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5605">کاغذ دیواری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5606">پرده و متعلقات - سایبان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5607">سیستم های قفسه بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5608">غرفه های نمایشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5701">کشتی سازی، تعمیرات کشتی، خدمات دریایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5702">راه آهن، خدمات ریلی (خدمات و تجهیزات)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5703">خدمات هواپیمایی، هلیکوپتری، فرودگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5704">فرودگاه های کشور</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5705">سازمانهای بنادر و کشتیرانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/10000">صنعت ساخت و ساز و املاک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/20000">مهندسین مشاور</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/90000">پیمانکاران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/140000">دکوراسیون داخلی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/190000">پارتیشن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/200000">پوششهای نما (داخلی و خارجی)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/270000">سیستم سرمایش و گرمایش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/300000">شومینه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/320000">املاک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/340000">مصالح ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/500000">چینی ها و سرامیک های بهداشتی، سرامیک های کف</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/550000">شیشه و آینه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/580000">عایق ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/650000">سازه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/680000">بالابر ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/710000">ماشین آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/740000">درب و پنجره - نما</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/800000">ابزار آلات ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/840000">تجهیزات ترافیکی و محیطی شهری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/870000">مبلمان پارکی - آب نما - فواره</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/880000">خدمات ساختمانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/890000">خدمات محوطه سازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/900000">نوسازی بنا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/910000">خدمات تخریب و تخلیه ساختمان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/920000">پزشکی، سلامتی، آرایشی - بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/930000">پزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/940000">مطب ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/960000">کلینیک ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1030000">محصولات پزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1040000">صنعت داروسازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1060000">داروخانه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1080000">ماشین آلات صنایع دارو سازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1120000">آزمایشگاه </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1170000">آزمایشگاه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1180000">فیزیوتراپی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1190000">آرایشی و بهداشتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1230000">شوینده ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1290000">دامپزشکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1300000">کلینیک دامپزشکی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1310000">فروش لوازم حیوانات </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1320000">زیبایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1330000">سالن های آرایشی و زیبایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1340000">صنعت نساجی، پوشاک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1350000">پوشاک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1410000">کیف و کفش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1440000">چرم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1480000">محصولات نساجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1530000">صنعت نساجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1610000">طلا و جواهر، زیور آلات، ساعت، عینک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1620000">طلا و جواهر، زیور آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1640000">سنگ های قیمتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1650000">آموزشگاه های طلاسازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1660000">نقره</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1670000">سایر زیور آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1680000">ساعت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1700000">عینک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1720000">لنز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1730000">ابزار، قطعات، آلیاژها و صنایع وابسته</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1740000">فراورده های انواع آلیاژ آهنی و غیر آهنی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/1890000"> تیرآهن - نبشی - میلگرد - ناودانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2010000">قطعات یدکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2050000">ابزار آلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2230000">لو له و اتصالات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2300000">لوله و اتصالات پلیمری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2310000">لوله کامپوزیتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2320000">سایر محصولات مورد استفاده در صنعت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2420000">صنعت فن آوری ارتباطات و اطلاعات IT,ICT</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2430000">خدمات کامپیوتر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2460000">تعمیرات کامپیوتر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2470000">قطعات یدکی کامپیوتر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2480000">خدمات شبکه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2490000">سیستم های تلفنی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2500000">اینترنت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2510000">خدمات ابری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2530000">مهندسین مشاور</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2560000">پیمانکاران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2570000">پیمانکاران در زمینه صنایع کامپیوتر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2580000">فرهنگی - آموزشی - ورزشی- هنری - سرگرمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2590000">فرهنگی - آموزشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2680000">صنعت فیلم - هنر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2710000">موسسات هنری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2720000">انواع برس، قلمو های نقاشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2740000">عکاسی و فیلمبرداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2750000">ساخت انیمیشن</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2760000">ورزشی - سرگرمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2840000">صنعت غذا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2850000">محصولات غذایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2880000"> آبغوره - سرکه - آبلیمو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/2900000">تنقلات ( چیپس، بیسکویت، شکلات، آبنبات و ...)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3030000">صنایع وابسته به غذا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3070000">کافه و رستوران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3080000">کافه و رستوران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3090000">تجهیزات کافه و رستوران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3100000">شیرینی و آجیل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3110000">شیرینی فروشی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3120000">آجیل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3130000">صنایع و تجهیزات تولید شیرینی و آجیل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3140000">خدمات غذایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3170000">صنعت حمل و نقل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3180000">خدمات دریایی، هوایی، ریلی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3260000">حمل و نقل داخلی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3280000">شرکت های اتوبوسرانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3290000">شرکت های خطوط هوایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3310000">پیک های موتوری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3340000">حمل و نقل بین الملل </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3360000">شرکت های پستی بین الملل</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3370000">مالی-بانکی، حقوقی، بیمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3380000">مالی - بانکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3460000">بیمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3490000">نمایندگی های بیمه</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3510000">حقوقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3540000">حسابرسی و مشاوره مالیاتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3550000">صنعت خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3560000">صنایع وابسته به خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3570000">ماشین آلات صنعت خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3580000">قطعات خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3590000">کولر اتومبیل </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3630000">سایر قطعات خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3640000">انواع خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3700000">خدمات پس از فروش خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3710000">خدمات پس از فروش خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3720000">قطعات یدکی خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3730000">مهندسی خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3750000">مدیریت کنترل کیفیت صنعت خودرو</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3760000">صنعت برق، الکترونیک و مخابرات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3770000">مشاوره در صنعت برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3800000">پیمانکاران در زمینه صنعت برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3810000">پیمانکاران در زمینه صنایع برق و مخابرات </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3820000">قطعات و محصولات الکترونیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3860000">تجهیزات برق اضطراری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3870000">تابلو صنعتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/3960000">واحد هیدرولیک برقی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4060000">خدمات برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4080000">تعمیرات صنعت برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4090000">صنایع دستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4100000">صنعت فرش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4120000">آموزشگاه های بافت فرش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4130000">کارگاه ها و شرکت های بافت فرش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4140000">نخ و سایر قطعات مربوط به فرش</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4150000">صنایع دستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4170000">آموزشگاه های صنایع دستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4180000">کارگاه ها و شرکت های صنایع دستی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4190000">لوازم خانگی، اداری، فروشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4200000">لوازم خانگی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4260000">سرویس خواب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4270000">ترازوهای خانگی و سایر ترازوهای کوچک </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4290000">لوازم اداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4310000">مبلمان اداری </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4340000">لوازم فروشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4410000">تجهیزات فروشگاهی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4420000">صنعت کشاورزی -دامپروری - ماهیگیری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4430000">صنعت کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4520000">وسایل برقی کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4540000">پیمانکاران در زمینه کشاورزی - محیط زیست - جنگلداری - منابع طبیعی - فضای سبز</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4560000">مواد، تجهیزات و خدمات کنترل آفت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4570000">محصولات کشاورزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4600000">صیفی جات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4620000">غلات (برنج، گندم، جو، ذرت)</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4670000">انواع گل و گیاه و بذر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4690000">انواع بذر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4700000">صنعت دامپروری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4770000">مهندسین مشاور در زمینه دامداری </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4780000">پیمانکاران در زمینه دامپروری </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4790000">صنعت ماهیگیری و شیلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4800000">خوراک آبزیان</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4810000">مهندسین مشاور در زمینه ماهیگیری و شیلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4830000">آبزیان آکواریومی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4840000">صنعت معدن و منابع طبیعی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4850000">صنایع معدنی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4900000">خدمات زیست محیطی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4930000">دفع زباله</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4950000">انرژی، آب، برق</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4970000">سوخت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4980000">سلول های سوختی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/4990000">انرژی های سالم</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5010000">صنعت گردشگری و مهاجرت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5020000">خدمات مسافرتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5050000">خدمات مهاجرت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5080000">خدمات اخذ ویزا</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5090000">تجهیزات سفر</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5110000">صنعت تبلیغات و ارتباطات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5120000">خدمات تبلیغات و بازاریابی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5170000">بانک های اطلاعات و اطلاع رسانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5180000">سایت های اطلاع رسانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5190000">نشریات و مجلات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5220000">بازرگانی، واردات و صادرات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5230000">واردات و صادرات</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5270000">خدمات بازرگانی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5310000">صنایع شیمیایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5320000">ماشین آلات و تجهیزات تولیدات شیمیایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5340000">تجهیزات تولید مواد شیمیایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5350000">محصولات شیمیایی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5420000">صنعت پلاستیک</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5430000">ماشین آلات و تجهیزات تولیدات پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5460000">تجهیزات تولید مواد پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5470000">محصولات پلاستیکی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5610000">صنعت آب و فاضلاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5620000">خدمات وابسته به آب و فاضلاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5660000">تجهیزات صنعت آب و فاضلاب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5670000">واتر پمپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5680000">کنتورهای آب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5690000">تجهیزات دبی سنجی و کنتورهای هوشمند آب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5700000">صنعت نفت و گاز و پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5710000">تجهیزات و پالایشگاه های نفت، گاز و پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5760000">محصولات نفت، گاز و پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5770000">فرآورده های نفتی ، گازی و پتروشیمی - سوخت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5780000">خدمات نفت، گاز و پتروشیمی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5820000">صنعت، تولید، تجهیزات وابسته</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/5830000">ماشین آلات و تجهیزات صنعت و تولید</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6000000">عایق ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6030000">ریخته گری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6080000">سایر تجهیزات وابسته صنعت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6180000">کشتی سازی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6210000">بالابر ها </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6250000">نقاله ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6260000">مهندسین مشاور صنایع</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6290000">پیمانکاران صنایع</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6330000">سندیکاها - تعاونیها و انجمن ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6340000">اتحادیه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6350000">اتحادیه ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6360000">انجمن ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6370000">ngo ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6380000">سندیکاها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6400000">سایر تشکل ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6410000">سایر تشکل ها</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6420000">صنعت چاپ ، بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6430000">ماشین آلات و تجهیزات صنعت چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6470000">دستگا های چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6510000">صنعت بسته بندی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6570000">کاغذ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6620000">خدمات چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6670000">تعمیرات صنعت چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6680000">خدمات پس از فروش صنعت چاپ</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6700000">صنعت چوب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6710000">تجهیزات و ماشین آلات صنعت چوب</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6740000">محصولات چوبی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6810000">خدمات </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6820000">مشاوره و مدیریت</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6870000">برگزاری همایش، نمایشگاه و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6900000">برگزاری مراسم، جشن ها و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6910000">تشریفات مجالس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6920000">لوازم و تجهیزات کرایه ای مجالس</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6930000">بازرسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6940000">صدور گواهی بازرسی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6960000">کاریابی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/6990000">صدور گواهینامه، ISO و ...</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7020000">صدور انواع گواهی های ISO</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7030000">خدمات نظافتی و انبارداری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7050000">قالیشویی و رفوگری</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7100000">دفاتر و سازمان های دولتی و خارجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7110000">ادارات دولتی (وزارت خانه ها - سازمانها و ...) </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7150000">دفاتر پلیس +10</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7160000">سفارت ها و موسسات خارجی در ایران  </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7190000">شرکت های خارجی در ایران</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7200000">پیمانکاران خارجی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7220000">خدمات ایمنی و امنیتی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7230000">سیستم و خدمات امنیتی آتش سوزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7240000">سیستم های هشدار دهنده و ایمنی آتش سوزی</a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7260000">تجهیزات و خدمات امنیتی </a><br>
<a href="http://www.tolidat.ir/company/type/تولیدی/category/7310000">سیستم های حفاظتی و دوربین مدار بسته</a><br>
